---
- hosts: ws
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Delete old Artifact
      file: 
        path: /opt/qa/spg/*.jar
        state: absent

    - name: get the PID 
      shell:  lsof -t -i :8082    
      register: pid_output
      tags: 
        - a
    - name: read data
      debug:     
         var: pid_output
      tags:
        - b   
    - name: Kill running App   
      shell: "Kill -9 {{ pid_output.stdout }}"
      when: pid_output.stdout != ''  

    - name: Download New Artifact
      get_url: 
         url: http://34.201.161.49:8081/artifactory/geolocation/geo/bio_17.jar
         dest: /opt/qa/spg
         url_username: admin
         url_password: password

    - name: Run the App
      shell: nohup java -jar /opt/qa/spg/*.jar > /opt/qa/spg.log 2>&1 &      